const fs = require('fs')

exports.conselhob = [
   "⛓️✨ É tão fácil acreditar que tudo depende só de você... mas shhh, deixa Deus guiar seus passos. Ele cuida de você melhor do que qualquer um jamais poderia... ❤️ Sl 37:5",
   "⚠️ Cuidado com esse arzinho de superioridade... a arrogância sempre leva à queda. Não quero ver você se machucando, ok? Prov 16:18",
   "💎 Quer investir no seu futuro? Seja generoso... quanto mais você dá, mais luz você espalha — e ela sempre volta. Lc 6:38",
   "🤐 Quando em dúvida, fique quietinho... palavras sem pensar podem ser lâminas. Pv 17:27",
   "📖 Estuda, meu bem... o conhecimento te protege. E a Bíblia é a lâmina mais afiada que você pode carregar. Os 4:6",
   "❗Sim, pessoas mentem... então, analise tudo com cuidado. Promete que vai pensar antes de confiar? Pv 14:15",
   "⌛ Autocontrole é um poder precioso... quem consegue se dominar pode conquistar tudo — até meu coração. Pv 16:32",
   "☀️ Começa seu dia entregando tudo a Deus... deixa Ele te abraçar. Sl 37:5",
   "🕯️ A Palavra é sua luz na escuridão... nunca ande sem ela. Sl 119:105",
   "⏳ Aproveita cada segundo. O agora é tudo que temos. Ec 9:10",
   "❌ 'Não posso'? 'É impossível'? Tira isso da boca! Pra Deus nada é impossível, e eu acredito em você. Lc 1:37",
   "🕰️ O passado... deixa pra trás. Você é uma nova criatura agora. 2 Cor 5:17",
   "🔥 Nunca tome decisões com raiva... respira, se acalma. Depois, decide. Pv 14:17",
   "⛔ Amizades erradas te arrastam pro escuro... fuja delas. Pv 22:24",
   "🤝 Cultive amizades verdadeiras... um amigo de verdade vale mais que mil promessas. Pv 18:24",
   "🤫 Até o tolo parece sábio se ficar calado... silêncio é poder. Pv 17:28",
   "🫂 Você não nasceu pra viver só. Alguém precisa de você — e você precisa de alguém. Ec 4:9-11",
   "💸 Não se prenda ao que é material... nada disso vai com você no fim. Ec 5:15",
   "🎁 Dê sem esperar nada em troca... doar é amar. Mt 5:42",
   "😌 Não se preocupe com o amanhã... vive hoje comigo, tá bom? Mt 6:34",
   "👨‍👩‍👧 Ame sua família. Cuide deles com tudo o que você tem. 1Tm 5:8",
   "⚔️ Seja ousado no Senhor! Ele te deu poder, não medo. 2Tm 1:7",
   "✝️ Evite brigas... paciência é coisa rara, mas é linda. 2Tm 2:24",
   "✨ Agradeça. Em tudo. Até nas lágrimas. Isso agrada a Deus... e me encanta. 1Ts 5:18",
   "☠️ Más companhias corrompem... e eu não quero te perder pra escuridão. 1Cor 15:33",
   "🧠 Ouça. Aprenda. Aceite conselhos. Deus tem planos maiores do que você imagina. Pv 19:20-21",
   "🌀 Confiar só em si mesmo é perigoso... a sabedoria protege. Pv 28:26",
   "🛡️ Mantenha-se firme! Fé, coragem e força — e você será inabalável. 1Cor 16:13",
   "❤️‍ Não deixe o mal te vencer. Seja o bem, mesmo que doa. Rm 12:21",
   "☁️ A fé... é crer no que não se vê, mas se sente no fundo do peito. Hb 11:1",
   "🌸 Nada por egoísmo... pense nos outros com amor. É assim que você brilha. Fp 2:3-4",
   "☁️ Perdoe. O perdão te liberta... e faz o céu sorrir. Mt 6:14-15",
   "🕰️ Lembra do teu Criador... antes que os dias fiquem sombrios. Ele te conhece desde o começo. Ec 12:1",
   "❣️ Vai... segue teu coração. Mas lembra: cada escolha tem um julgamento. Ec 11:9",
   "✨ Ninguém pode te desprezar por ser jovem... seja exemplo, e todos te verão brilhar. 1Tm 4:12",
   "👑 Um jovem sábio vale mais que um rei tolo... nunca pare de aprender. Ec 4:13",
   "🤍 Repreenda com amor... respeite os mais velhos como pais. 1Tm 5:1",
   "⏳ O tempo passa... mas Deus permanece. Nunca se esqueça dEle. Ec 12:1"
]