const fs = require('fs')

exports.palavrasc = [
  "✨ *“Se você traçar metas absurdamente altas e falhar, seu fracasso será muito melhor que o sucesso de todos.”* – James Cameron, Cineasta",
  "⏳ *“O sucesso normalmente vem para quem está ocupado demais para procurá-lo.”* – Henry David Thoreau, filósofo",
  "☀️ *“A vida é melhor para aqueles que fazem o possível para ter o melhor.”* – John Wooden, treinador",
  "🔥 *“Empreendedores falham em média 3,8 vezes antes do sucesso. O segredo é a persistência.”* – Lisa M. Amos, executiva",
  "⚠️ *“Se você não está disposto a arriscar, esteja disposto a uma vida comum.”* – Jim Rohn, empreendedor",
  "🧠 *“Escolha uma ideia. Viva por ela. Deixe seu corpo ser tomado por essa ideia.”* – Swami Vivekananda",
  "💸 *“Pare de perseguir o dinheiro e comece a perseguir o sucesso.”* – Tony Hsieh",
  "🌈 *“Todos os seus sonhos podem se realizar se você tiver coragem.”* – Walt Disney",
  "💥 *“Ter sucesso é falhar várias vezes sem perder o entusiasmo.”* – Winston Churchill",
  "🔍 *“Só vemos a glória das pessoas de sucesso, não os sacrifícios.”* – Vaibhav Shah",
  "❤️ *“Sucesso? Para mim é paz interior.”* – Denzel Washington",
  "🛠️ *“Oportunidades não surgem. Você as cria.”* – Chris Grosser",
  "🌟 *“Não tente ser bem-sucedido. Seja valioso.”* – Albert Einstein",
  "🌿 *“Não sobrevive o mais forte, mas o que melhor se adapta.”* – Charles Darwin",
  "🎤 *“A melhor vingança é um sucesso estrondoso.”* – Frank Sinatra",
  "💡 *“Não falhei. Apenas descobri 10 mil jeitos que não funcionam.”* – Thomas Edison",
  "🧱 *“Use os tijolos que jogaram em você para construir algo.”* – David Brinkley",
  "✊ *“Ninguém te faz sentir inferior sem seu consentimento.”* – Eleanor Roosevelt",
  "🎯 *“O segredo da vida é encontrar seu destino... e cumpri-lo.”* – Henry Ford",
  "🔥 *“Se estiver passando pelo inferno, continue andando.”* – Churchill",
  "🎭 *“Uma provação pode ser uma bênção disfarçada.”* – Oscar Wilde",
  "⚖️ *“A linha entre insanidade e genialidade é o sucesso.”* – Bruce Feirstein",
  "🏹 *“Não tema largar o bom para buscar o ótimo.”* – John D. Rockefeller",
  "🦋 *“A felicidade é como uma borboleta... às vezes, pousa quando você menos espera.”* – Nathaniel Hawthorne",
  "🧩 *“Se você não consegue explicar de forma simples, não entendeu bem o assunto.”* – Einstein",
  "🛡️ *“Dois tipos vão te desmotivar: os que têm medo de tentar e os que temem que você vença.”* – Ray Goforth",
  "🚀 *“Comece de onde está. Use o que tem. Faça o que puder.”* – Arthur Ashe",
  "🎬 *“Meu papel favorito? Sempre o próximo.”* – Kevin Kline",
  "🎲 *“Quanto mais eu trabalho, mais sorte eu tenho.”* – Thomas Jefferson",
  "💭 *“O ponto de partida de qualquer conquista é o desejo.”* – Napoleon Hill"
]